

export class Countries {

    countryList: any =
    [

        { 'countryName': 'United States', 'countryAbbreviation': 'US' },
        { 'countryName': 'Canada', 'countryAbbreviation': 'CA' },
        { 'countryName': '-----------', 'countryAbbreviation': '' },
        { 'countryName': 'Afghanistan', 'countryAbbreviation': 'AF' },
        { 'countryName': 'Albania', 'countryAbbreviation': 'AL' },
        { 'countryName': 'Algeria', 'countryAbbreviation': 'DZ' },
        { 'countryName': 'American Samoa', 'countryAbbreviation': 'AS' },
        { 'countryName': 'Andorra', 'countryAbbreviation': 'AD' },
        { 'countryName': 'Angola', 'countryAbbreviation': 'AO' },
        { 'countryName': 'Anguilla', 'countryAbbreviation': 'AI' },
        { 'countryName': 'Antarctica', 'countryAbbreviation': 'AQ' },
        { 'countryName': 'Antigua and Barbuda', 'countryAbbreviation': 'AG' },
        { 'countryName': 'Argentina', 'countryAbbreviation': 'AR' },
        { 'countryName': 'Armenia', 'countryAbbreviation': 'AM' },
        { 'countryName': 'Aruba', 'countryAbbreviation': 'AW' },
        { 'countryName': 'Australia', 'countryAbbreviation': 'AU' },
        { 'countryName': 'Austria', 'countryAbbreviation': 'AT' },
        { 'countryName': 'Azerbaijan', 'countryAbbreviation': 'AZ' },
        { 'countryName': 'Bahamas', 'countryAbbreviation': 'BS' },
        { 'countryName': 'Bahrain', 'countryAbbreviation': 'BH' },
        { 'countryName': 'Bangladesh', 'countryAbbreviation': 'BD' },
        { 'countryName': 'Barbados', 'countryAbbreviation': 'BB' },
        { 'countryName': 'Belarus', 'countryAbbreviation': 'BY' },
        { 'countryName': 'Belgium', 'countryAbbreviation': 'BE' },
        { 'countryName': 'Belize', 'countryAbbreviation': 'BZ' },
        { 'countryName': 'Benin', 'countryAbbreviation': 'BJ' },
        { 'countryName': 'Bermuda', 'countryAbbreviation': 'BM' },
        { 'countryName': 'Bhutan', 'countryAbbreviation': 'BT' },
        { 'countryName': 'Bolivia', 'countryAbbreviation': 'BO' },
        { 'countryName': 'Bosnia and Herzegovina', 'countryAbbreviation': 'BA' },
        { 'countryName': 'Botswana', 'countryAbbreviation': 'BW' },
        { 'countryName': 'Bouvet Island', 'countryAbbreviation': 'BV' },
        { 'countryName': 'Brazil', 'countryAbbreviation': 'BR' },
        { 'countryName': 'British Indian Ocean Territory', 'countryAbbreviation': 'IO' },
        { 'countryName': 'Brunei Darussalam', 'countryAbbreviation': 'BN' },
        { 'countryName': 'Bulgaria', 'countryAbbreviation': 'BG' },
        { 'countryName': 'Burkina Faso', 'countryAbbreviation': 'BF' },
        { 'countryName': 'Burundi', 'countryAbbreviation': 'BI' },
        { 'countryName': 'Cambodia', 'countryAbbreviation': 'KH' },
        { 'countryName': 'Cameroon', 'countryAbbreviation': 'CM' },
        { 'countryName': 'Canada', 'countryAbbreviation': 'CA' },
        { 'countryName': 'Cape Verde', 'countryAbbreviation': 'CV' },
        { 'countryName': 'Cayman Islands', 'countryAbbreviation': 'KY' },
        { 'countryName': 'Central African Republic', 'countryAbbreviation': 'CF' },
        { 'countryName': 'Chad', 'countryAbbreviation': 'TD' },
        { 'countryName': 'Chile', 'countryAbbreviation': 'CL' },
        { 'countryName': 'China', 'countryAbbreviation': 'CN' },
        { 'countryName': 'Christmas Island', 'countryAbbreviation': 'CX' },
        { 'countryName': 'Cocos (Keeling) Islands', 'countryAbbreviation': 'CC' },
        { 'countryName': 'Colombia', 'countryAbbreviation': 'CO' },
        { 'countryName': 'Comoros', 'countryAbbreviation': 'KM' },
        { 'countryName': 'Congo', 'countryAbbreviation': 'CG' },
        { 'countryName': 'Cook Islands', 'countryAbbreviation': 'CK' },
        { 'countryName': 'Costa Rica', 'countryAbbreviation': 'CR' },
        { 'countryName': 'Cote D Ivoire (Ivory Coast)', 'countryAbbreviation': 'CI' },
        { 'countryName': 'Croatia (Hrvatska)', 'countryAbbreviation': 'HR' },
        { 'countryName': 'Cuba', 'countryAbbreviation': 'CU' },
        { 'countryName': 'Cyprus', 'countryAbbreviation': 'CY' },
        { 'countryName': 'Czech Republic', 'countryAbbreviation': 'CZ' },
        { 'countryName': 'Denmark', 'countryAbbreviation': 'DK' },
        { 'countryName': 'Djibouti', 'countryAbbreviation': 'DJ' },
        { 'countryName': 'Dominica', 'countryAbbreviation': 'DM' },
        { 'countryName': 'Dominican Republic', 'countryAbbreviation': 'DO' },
        { 'countryName': 'East Timor', 'countryAbbreviation': 'TP' },
        { 'countryName': 'Ecuador', 'countryAbbreviation': 'EC' },
        { 'countryName': 'Egypt', 'countryAbbreviation': 'EG' },
        { 'countryName': 'El Salvador', 'countryAbbreviation': 'SV' },
        { 'countryName': 'Equatorial Guinea', 'countryAbbreviation': 'GQ' },
        { 'countryName': 'Eritrea', 'countryAbbreviation': 'ER' },
        { 'countryName': 'Estonia', 'countryAbbreviation': 'EE' },
        { 'countryName': 'Ethiopia', 'countryAbbreviation': 'ET' },
        { 'countryName': 'Falkland Islands (Malvinas)', 'countryAbbreviation': 'FK' },
        { 'countryName': 'Faroe Islands', 'countryAbbreviation': 'FO' },
        { 'countryName': 'Fiji', 'countryAbbreviation': 'FJ' },
        { 'countryName': 'Finland', 'countryAbbreviation': 'FI' },
        { 'countryName': 'France', 'countryAbbreviation': 'FR' },
        { 'countryName': 'French Guiana', 'countryAbbreviation': 'GF' },
        { 'countryName': 'French Polynesia', 'countryAbbreviation': 'PF' },
        { 'countryName': 'French Southern Territories', 'countryAbbreviation': 'TF' },
        { 'countryName': 'Gabon', 'countryAbbreviation': 'GA' },
        { 'countryName': 'Gambia', 'countryAbbreviation': 'GM' },
        { 'countryName': 'Gaza', 'countryAbbreviation': 'GZ' },
        { 'countryName': 'Georgia', 'countryAbbreviation': 'GE' },
        { 'countryName': 'Germany', 'countryAbbreviation': 'DE' },
        { 'countryName': 'Ghana', 'countryAbbreviation': 'GH' },
        { 'countryName': 'Gibraltar', 'countryAbbreviation': 'GI' },
        { 'countryName': 'Greece', 'countryAbbreviation': 'GR' },
        { 'countryName': 'Greenland', 'countryAbbreviation': 'GL' },
        { 'countryName': 'Grenada', 'countryAbbreviation': 'GD' },
        { 'countryName': 'Guadeloupe', 'countryAbbreviation': 'GP' },
        { 'countryName': 'Guam', 'countryAbbreviation': 'GU' },
        { 'countryName': 'Guatemala', 'countryAbbreviation': 'GT' },
        { 'countryName': 'Guinea', 'countryAbbreviation': 'GN' },
        { 'countryName': 'Guinea-Bissau', 'countryAbbreviation': 'GW' },
        { 'countryName': 'Guyana', 'countryAbbreviation': 'GY' },
        { 'countryName': 'Haiti', 'countryAbbreviation': 'HT' },
        { 'countryName': 'Heard and McDonald Islands', 'countryAbbreviation': 'HM' },
        { 'countryName': 'Honduras', 'countryAbbreviation': 'HN' },
        { 'countryName': 'Hong Kong', 'countryAbbreviation': 'HK' },
        { 'countryName': 'Hungary', 'countryAbbreviation': 'HU' },
        { 'countryName': 'Iceland', 'countryAbbreviation': 'IS' },
        { 'countryName': 'India', 'countryAbbreviation': 'IN' },
        { 'countryName': 'Indonesia', 'countryAbbreviation': 'ID' },
        { 'countryName': 'Iran', 'countryAbbreviation': 'IR' },
        { 'countryName': 'Iraq', 'countryAbbreviation': 'IQ' },
        { 'countryName': 'Ireland', 'countryAbbreviation': 'IE' },
        { 'countryName': 'Israel', 'countryAbbreviation': 'IL' },
        { 'countryName': 'Italy', 'countryAbbreviation': 'IT' },
        { 'countryName': 'Jamaica', 'countryAbbreviation': 'JM' },
        { 'countryName': 'Japan', 'countryAbbreviation': 'JP' },
        { 'countryName': 'Jordan', 'countryAbbreviation': 'JO' },
        { 'countryName': 'Kazakhstan', 'countryAbbreviation': 'KZ' },
        { 'countryName': 'Kenya', 'countryAbbreviation': 'KE' },
        { 'countryName': 'Kiribati', 'countryAbbreviation': 'KI' },
        { 'countryName': 'Korea (North)', 'countryAbbreviation': 'KP' },
        { 'countryName': 'Korea (South)', 'countryAbbreviation': 'KR' },
        { 'countryName': 'Kuwait', 'countryAbbreviation': 'KW' },
        { 'countryName': 'Kyrgyzstan', 'countryAbbreviation': 'KG' },
        { 'countryName': 'Laos', 'countryAbbreviation': 'LA' },
        { 'countryName': 'Latvia', 'countryAbbreviation': 'LV' },
        { 'countryName': 'Lebanon', 'countryAbbreviation': 'LB' },
        { 'countryName': 'Lesotho', 'countryAbbreviation': 'LS' },
        { 'countryName': 'Liberia', 'countryAbbreviation': 'LR' },
        { 'countryName': 'Libya', 'countryAbbreviation': 'LY' },
        { 'countryName': 'Liechtenstein', 'countryAbbreviation': 'LI' },
        { 'countryName': 'Lithuania', 'countryAbbreviation': 'LT' },
        { 'countryName': 'Luxembourg', 'countryAbbreviation': 'LU' },
        { 'countryName': 'Macau', 'countryAbbreviation': 'MO' },
        { 'countryName': 'Macedonia', 'countryAbbreviation': 'MK' },
        { 'countryName': 'Madagascar', 'countryAbbreviation': 'MG' },
        { 'countryName': 'Malawi', 'countryAbbreviation': 'MW' },
        { 'countryName': 'Malaysia', 'countryAbbreviation': 'MY' },
        { 'countryName': 'Maldives', 'countryAbbreviation': 'MV' },
        { 'countryName': 'Mali', 'countryAbbreviation': 'ML' },
        { 'countryName': 'Malta', 'countryAbbreviation': 'MT' },
        { 'countryName': 'Marshall Islands', 'countryAbbreviation': 'MH' },
        { 'countryName': 'Martinique', 'countryAbbreviation': 'MQ' },
        { 'countryName': 'Mauritania', 'countryAbbreviation': 'MR' },
        { 'countryName': 'Mauritius', 'countryAbbreviation': 'MU' },
        { 'countryName': 'Mayotte', 'countryAbbreviation': 'YT' },
        { 'countryName': 'Mexico', 'countryAbbreviation': 'MX' },
        { 'countryName': 'Micronesia', 'countryAbbreviation': 'FM' },
        { 'countryName': 'Moldova', 'countryAbbreviation': 'MD' },
        { 'countryName': 'Monaco', 'countryAbbreviation': 'MC' },
        { 'countryName': 'Mongolia', 'countryAbbreviation': 'MN' },
        { 'countryName': 'Montserrat', 'countryAbbreviation': 'MS' },
        { 'countryName': 'Morocco', 'countryAbbreviation': 'MA' },
        { 'countryName': 'Mozambique', 'countryAbbreviation': 'MZ' },
        { 'countryName': 'Myanmar', 'countryAbbreviation': 'MM' },
        { 'countryName': 'Namibia', 'countryAbbreviation': 'NA' },
        { 'countryName': 'Nauru', 'countryAbbreviation': 'NR' },
        { 'countryName': 'Nepal', 'countryAbbreviation': 'NP' },
        { 'countryName': 'Netherlands', 'countryAbbreviation': 'NL' },
        { 'countryName': 'Netherlands Antilles', 'countryAbbreviation': 'AN' },
        { 'countryName': 'New Caledonia', 'countryAbbreviation': 'NC' },
        { 'countryName': 'New Zealand', 'countryAbbreviation': 'NZ' },
        { 'countryName': 'Nicaragua', 'countryAbbreviation': 'NI' },
        { 'countryName': 'Niger', 'countryAbbreviation': 'NE' },
        { 'countryName': 'Nigeria', 'countryAbbreviation': 'NG' },
        { 'countryName': 'Niue', 'countryAbbreviation': 'NU' },
        { 'countryName': 'Norfolk Island', 'countryAbbreviation': 'NF' },
        { 'countryName': 'Northern Mariana Islands', 'countryAbbreviation': 'MP' },
        { 'countryName': 'Norway', 'countryAbbreviation': 'NO' },
        { 'countryName': 'Oman', 'countryAbbreviation': 'OM' },
        { 'countryName': 'Pakistan', 'countryAbbreviation': 'PK' },
        { 'countryName': 'Palau', 'countryAbbreviation': 'PW' },
        { 'countryName': 'Panama', 'countryAbbreviation': 'PA' },
        { 'countryName': 'Papua New Guinea', 'countryAbbreviation': 'PG' },
        { 'countryName': 'Paraguay', 'countryAbbreviation': 'PY' },
        { 'countryName': 'Peru', 'countryAbbreviation': 'PE' },
        { 'countryName': 'Philippines', 'countryAbbreviation': 'PH' },
        { 'countryName': 'Pitcairn', 'countryAbbreviation': 'PN' },
        { 'countryName': 'Poland', 'countryAbbreviation': 'PL' },
        { 'countryName': 'Portugal', 'countryAbbreviation': 'PT' },
        { 'countryName': 'Puerto Rico', 'countryAbbreviation': 'PR' },
        { 'countryName': 'Qatar', 'countryAbbreviation': 'QA' },
        { 'countryName': 'Reunion', 'countryAbbreviation': 'RE' },
        { 'countryName': 'Romania', 'countryAbbreviation': 'RO' },
        { 'countryName': 'Russian Federation', 'countryAbbreviation': 'RU' },
        { 'countryName': 'Rwanda', 'countryAbbreviation': 'RW' },
        { 'countryName': 'Saint Kitts and Nevis', 'countryAbbreviation': 'KN' },
        { 'countryName': 'Saint Lucia', 'countryAbbreviation': 'LC' },
        { 'countryName': 'Saint Vincent and the Grenadines', 'countryAbbreviation': 'VC' },
        { 'countryName': 'Samoa', 'countryAbbreviation': 'WS' },
        { 'countryName': 'San Marino', 'countryAbbreviation': 'SM' },
        { 'countryName': 'Sao Tome and Principe', 'countryAbbreviation': 'ST' },
        { 'countryName': 'Saudi Arabia', 'countryAbbreviation': 'SA' },
        { 'countryName': 'Senegal', 'countryAbbreviation': 'SN' },
        { 'countryName': 'Seychelles', 'countryAbbreviation': 'SC' },
        { 'countryName': 'Sierra Leone', 'countryAbbreviation': 'SL' },
        { 'countryName': 'Singapore', 'countryAbbreviation': 'SG' },
        { 'countryName': 'Slovak Republic', 'countryAbbreviation': 'SK' },
        { 'countryName': 'Slovenia', 'countryAbbreviation': 'SI' },
        { 'countryName': 'Solomon Islands', 'countryAbbreviation': 'SB' },
        { 'countryName': 'Somalia', 'countryAbbreviation': 'SO' },
        { 'countryName': 'South Africa', 'countryAbbreviation': 'ZA' },
        { 'countryName': 'Spain', 'countryAbbreviation': 'ES' },
        { 'countryName': 'Sri Lanka', 'countryAbbreviation': 'LK' },
        { 'countryName': 'St. Helena', 'countryAbbreviation': 'SH' },
        { 'countryName': 'St. Pierre and Miquelon', 'countryAbbreviation': 'PM' },
        { 'countryName': 'Sudan', 'countryAbbreviation': 'SD' },
        { 'countryName': 'Suriname', 'countryAbbreviation': 'SR' },
        { 'countryName': 'Svalbard and Jan Mayen Islands', 'countryAbbreviation': 'SJ' },
        { 'countryName': 'Swaziland', 'countryAbbreviation': 'SZ' },
        { 'countryName': 'Sweden', 'countryAbbreviation': 'SE' },
        { 'countryName': 'Switzerland', 'countryAbbreviation': 'CH' },
        { 'countryName': 'Syria', 'countryAbbreviation': 'SY' },
        { 'countryName': 'Taiwan', 'countryAbbreviation': 'TW' },
        { 'countryName': 'Tajikistan', 'countryAbbreviation': 'TJ' },
        { 'countryName': 'Tanzania', 'countryAbbreviation': 'TZ' },
        { 'countryName': 'Thailand', 'countryAbbreviation': 'TH' },
        { 'countryName': 'Togo', 'countryAbbreviation': 'TG' },
        { 'countryName': 'Tokelau', 'countryAbbreviation': 'TK' },
        { 'countryName': 'Tonga', 'countryAbbreviation': 'TO' },
        { 'countryName': 'Trinidad and Tobago', 'countryAbbreviation': 'TT' },
        { 'countryName': 'Tunisia', 'countryAbbreviation': 'TN' },
        { 'countryName': 'Turkey', 'countryAbbreviation': 'TR' },
        { 'countryName': 'Turkmenistan', 'countryAbbreviation': 'TM' },
        { 'countryName': 'Turks and Caicos Islands', 'countryAbbreviation': 'TC' },
        { 'countryName': 'Tuvalu', 'countryAbbreviation': 'TV' },
        { 'countryName': 'Uganda', 'countryAbbreviation': 'UG' },
        { 'countryName': 'Ukraine', 'countryAbbreviation': 'UA' },
        { 'countryName': 'United Arab Emirates', 'countryAbbreviation': 'AE' },
        { 'countryName': 'United Kingdom', 'countryAbbreviation': 'GB' },
        { 'countryName': 'United States', 'countryAbbreviation': 'US' },
        { 'countryName': 'Uruguay', 'countryAbbreviation': 'UY' },
        { 'countryName': 'US Minor Outlying Islands', 'countryAbbreviation': 'UM' },
        { 'countryName': 'Uzbekistan', 'countryAbbreviation': 'UZ' },
        { 'countryName': 'Vanuatu', 'countryAbbreviation': 'VU' },
        { 'countryName': 'Vatican City State (Holy See)', 'countryAbbreviation': 'VA' },
        { 'countryName': 'Venezuela', 'countryAbbreviation': 'VE' },
        { 'countryName': 'Viet Nam', 'countryAbbreviation': 'VN' },
        { 'countryName': 'Virgin Islands (British)', 'countryAbbreviation': 'VG' },
        { 'countryName': 'Virgin Islands (U.S.)', 'countryAbbreviation': 'VI' },
        { 'countryName': 'Wallis and Futuna Islands', 'countryAbbreviation': 'WF' },
        { 'countryName': 'West Bank', 'countryAbbreviation': 'WB' },
        { 'countryName': 'Western Sahara', 'countryAbbreviation': 'EH' },
        { 'countryName': 'Yemen', 'countryAbbreviation': 'YE' },
        { 'countryName': 'Yugoslavia', 'countryAbbreviation': 'YU' },
        { 'countryName': 'Zaire', 'countryAbbreviation': 'ZR' },
        { 'countryName': 'Zambia', 'countryAbbreviation': 'ZM' },
        { 'countryName': 'Zimbabwe', 'countryAbbreviation': 'ZW' }
    ];
}