

export class States {


    stateList: any =
    [
        { 'stateAbbreviation': 'AL', 'stateName': 'Alabama' },
        { 'stateAbbreviation': 'AK', 'stateName': 'Alaska' },
        { 'stateAbbreviation': 'AZ', 'stateName': 'Arizona' },
        { 'stateAbbreviation': 'AR', 'stateName': 'Arkansas' },
        { 'stateAbbreviation': 'CA', 'stateName': 'California' },
        { 'stateAbbreviation': 'CO', 'stateName': 'Colorado' },
        { 'stateAbbreviation': 'CT', 'stateName': 'Connecticut' },
        { 'stateAbbreviation': 'DC', 'stateName': 'D.C.' },
        { 'stateAbbreviation': 'DE', 'stateName': 'Delaware' },
        { 'stateAbbreviation': 'FL', 'stateName': 'Florida' },
        { 'stateAbbreviation': 'GA', 'stateName': 'Georgia' },
        { 'stateAbbreviation': 'HI', 'stateName': 'Hawaii' },
        { 'stateAbbreviation': 'ID', 'stateName': 'Idaho' },
        { 'stateAbbreviation': 'IL', 'stateName': 'Illinois' },
        { 'stateAbbreviation': 'IN', 'stateName': 'Indiana' },
        { 'stateAbbreviation': 'IA', 'stateName': 'Iowa' },
        { 'stateAbbreviation': 'KS', 'stateName': 'Kansas' },
        { 'stateAbbreviation': 'KY', 'stateName': 'Kentucky' },
        { 'stateAbbreviation': 'LA', 'stateName': 'Louisiana' },
        { 'stateAbbreviation': 'ME', 'stateName': 'Maine' },
        { 'stateAbbreviation': 'MD', 'stateName': 'Maryland' },
        { 'stateAbbreviation': 'MA', 'stateName': 'Massachusetts' },
        { 'stateAbbreviation': 'MI', 'stateName': 'Michigan' },
        { 'stateAbbreviation': 'MN', 'stateName': 'Minnesota' },
        { 'stateAbbreviation': 'MS', 'stateName': 'Mississippi' },
        { 'stateAbbreviation': 'MO', 'stateName': 'Missouri' },
        { 'stateAbbreviation': 'MT', 'stateName': 'Montana' },
        { 'stateAbbreviation': 'NE', 'stateName': 'Nebraska' },
        { 'stateAbbreviation': 'NV', 'stateName': 'Nevada' },
        { 'stateAbbreviation': 'NH', 'stateName': 'New Hampshire' },
        { 'stateAbbreviation': 'NJ', 'stateName': 'New Jersey' },
        { 'stateAbbreviation': 'NM', 'stateName': 'New Mexico' },
        { 'stateAbbreviation': 'NY', 'stateName': 'New York' },
        { 'stateAbbreviation': 'NC', 'stateName': 'North Carolina' },
        { 'stateAbbreviation': 'ND', 'stateName': 'North Dakota' },
        { 'stateAbbreviation': 'OH', 'stateName': 'Ohio' },
        { 'stateAbbreviation': 'OK', 'stateName': 'Oklahoma' },
        { 'stateAbbreviation': 'OR', 'stateName': 'Oregon' },
        { 'stateAbbreviation': 'PA', 'stateName': 'Pennsylvania' },
        { 'stateAbbreviation': 'RI', 'stateName': 'Rhode Island' },
        { 'stateAbbreviation': 'SC', 'stateName': 'South Carolina' },
        { 'stateAbbreviation': 'SD', 'stateName': 'South Dakota' },
        { 'stateAbbreviation': 'TN', 'stateName': 'Tennessee' },
        { 'stateAbbreviation': 'TX', 'stateName': 'Texas' },
        { 'stateAbbreviation': 'UT', 'stateName': 'Utah' },
        { 'stateAbbreviation': 'VT', 'stateName': 'Vermont' },
        { 'stateAbbreviation': 'VA', 'stateName': 'Virginia' },
        { 'stateAbbreviation': 'WA', 'stateName': 'Washington' },
        { 'stateAbbreviation': 'WV', 'stateName': 'West Virginia' },
        { 'stateAbbreviation': 'WI', 'stateName': 'Wisconsin' },
        { 'stateAbbreviation': 'WY', 'stateName': 'Wyoming' },
        { 'stateAbbreviation': 'AB', 'stateName': 'Alberta' },
        { 'stateAbbreviation': 'BC', 'stateName': 'British Columbia' },
        { 'stateAbbreviation': 'MB', 'stateName': 'Manitoba' },
        { 'stateAbbreviation': 'NB', 'stateName': 'New Brunswick' },
        { 'stateAbbreviation': 'NL', 'stateName': 'Newfoundland and Labrador' },
        { 'stateAbbreviation': 'NT', 'stateName': 'Northwest Territories' },
        { 'stateAbbreviation': 'NS', 'stateName': 'Nova Scotia' },
        { 'stateAbbreviation': 'NU', 'stateName': 'Nunavut' },
        { 'stateAbbreviation': 'ON', 'stateName': 'Ontario' },
        { 'stateAbbreviation': 'PE', 'stateName': 'Prince Edward Island' },
        { 'stateAbbreviation': 'QC', 'stateName': 'Quebec' },
        { 'stateAbbreviation': 'SK', 'stateName': 'Saskatchewan' },
        { 'stateAbbreviation': 'YT', 'stateName': 'Yukon Territories' }
    ];
}